server:
 servlet:
  context-path: /lemon
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.98.164.194:3306/api-runner
    username: root
    password: root
    
logging:
  level:
   root: info
   com.lemon.mapper: trace